GET http://localhost:3001/api/persons/

###

DELETE http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons/

content-type: application/json

{
    "name":"Test Test",
    "number":"040-1234567"
}