GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/2
###
DELETE http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons

HTTP/1.1 content-type: application/json
{
    "name": "Test",
    "number": "040-1234567"
}